#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="miniproyecto")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAeronave(tblAeronave instance);
    partial void UpdatetblAeronave(tblAeronave instance);
    partial void DeletetblAeronave(tblAeronave instance);
    partial void InserttblPiloto(tblPiloto instance);
    partial void UpdatetblPiloto(tblPiloto instance);
    partial void DeletetblPiloto(tblPiloto instance);
    partial void InserttblTrayecto(tblTrayecto instance);
    partial void UpdatetblTrayecto(tblTrayecto instance);
    partial void DeletetblTrayecto(tblTrayecto instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    partial void InserttblUsuarioVuelo(tblUsuarioVuelo instance);
    partial void UpdatetblUsuarioVuelo(tblUsuarioVuelo instance);
    partial void DeletetblUsuarioVuelo(tblUsuarioVuelo instance);
    partial void InserttblVuelo(tblVuelo instance);
    partial void UpdatetblVuelo(tblVuelo instance);
    partial void DeletetblVuelo(tblVuelo instance);
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::MODEL.Properties.Settings.Default.miniproyectoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAeronave> tblAeronaves
		{
			get
			{
				return this.GetTable<tblAeronave>();
			}
		}
		
		public System.Data.Linq.Table<tblPiloto> tblPilotos
		{
			get
			{
				return this.GetTable<tblPiloto>();
			}
		}
		
		public System.Data.Linq.Table<tblTrayecto> tblTrayectos
		{
			get
			{
				return this.GetTable<tblTrayecto>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuarios
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuarioVuelo> tblUsuarioVuelos
		{
			get
			{
				return this.GetTable<tblUsuarioVuelo>();
			}
		}
		
		public System.Data.Linq.Table<tblVuelo> tblVuelos
		{
			get
			{
				return this.GetTable<tblVuelo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procInserClient")]
		public int procInserClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identification", DbType="VarChar(20)")] string identification, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(10)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(10)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(40)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="VarChar(1)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identification, password, userName, name, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procInsertAirplane")]
		public int procInsertAirplane([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Model", DbType="VarChar(20)")] string model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitsAvailable", DbType="Int")] System.Nullable<int> unitsAvailable, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassengerCapacity", DbType="Int")] System.Nullable<int> passengerCapacity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeightCapacity", DbType="VarChar(20)")] string weightCapacity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Autonomy", DbType="Int")] System.Nullable<int> autonomy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), model, unitsAvailable, passengerCapacity, weightCapacity, autonomy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procInsertFlight")]
		public int procInsertFlight([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartureDate", DbType="VarChar(12)")] string departureDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartureTime", DbType="VarChar(5)")] string departureTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnDate", DbType="VarChar(12)")] string returnDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnTime", DbType="VarChar(5)")] string returnTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRoute", DbType="Int")] System.Nullable<int> idRoute, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAirplane", DbType="Int")] System.Nullable<int> idAirplane, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPilot", DbType="Int")] System.Nullable<int> idPilot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameFlight", DbType="VarChar(50)")] string nameFlight)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), departureDate, departureTime, returnDate, returnTime, idRoute, idAirplane, idPilot, nameFlight);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procInsertPilot")]
		public int procInsertPilot([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(40)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identification", DbType="VarChar(20)")] string identification)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, identification);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procInsertRoute")]
		public int procInsertRoute([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(15)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Origin", DbType="VarChar(20)")] string origin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Destination", DbType="VarChar(20)")] string destination, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="VarChar(20)")] string price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FlightTime", DbType="VarChar(10)")] string flightTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Miles", DbType="VarChar(15)")] string miles)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code, origin, destination, price, flightTime, miles);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAeronave")]
	public partial class tblAeronave : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAeronave;
		
		private string _Modelo;
		
		private System.Nullable<int> _UnidadesDisponibles;
		
		private System.Nullable<int> _CapacidadPasajeros;
		
		private string _CapacidadCarga;
		
		private System.Nullable<int> _Autonomia;
		
		private EntitySet<tblVuelo> _tblVuelos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAeronaveChanging(int value);
    partial void OnIdAeronaveChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnUnidadesDisponiblesChanging(System.Nullable<int> value);
    partial void OnUnidadesDisponiblesChanged();
    partial void OnCapacidadPasajerosChanging(System.Nullable<int> value);
    partial void OnCapacidadPasajerosChanged();
    partial void OnCapacidadCargaChanging(string value);
    partial void OnCapacidadCargaChanged();
    partial void OnAutonomiaChanging(System.Nullable<int> value);
    partial void OnAutonomiaChanged();
    #endregion
		
		public tblAeronave()
		{
			this._tblVuelos = new EntitySet<tblVuelo>(new Action<tblVuelo>(this.attach_tblVuelos), new Action<tblVuelo>(this.detach_tblVuelos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAeronave", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAeronave
		{
			get
			{
				return this._IdAeronave;
			}
			set
			{
				if ((this._IdAeronave != value))
				{
					this.OnIdAeronaveChanging(value);
					this.SendPropertyChanging();
					this._IdAeronave = value;
					this.SendPropertyChanged("IdAeronave");
					this.OnIdAeronaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(20)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadesDisponibles", DbType="Int")]
		public System.Nullable<int> UnidadesDisponibles
		{
			get
			{
				return this._UnidadesDisponibles;
			}
			set
			{
				if ((this._UnidadesDisponibles != value))
				{
					this.OnUnidadesDisponiblesChanging(value);
					this.SendPropertyChanging();
					this._UnidadesDisponibles = value;
					this.SendPropertyChanged("UnidadesDisponibles");
					this.OnUnidadesDisponiblesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacidadPasajeros", DbType="Int")]
		public System.Nullable<int> CapacidadPasajeros
		{
			get
			{
				return this._CapacidadPasajeros;
			}
			set
			{
				if ((this._CapacidadPasajeros != value))
				{
					this.OnCapacidadPasajerosChanging(value);
					this.SendPropertyChanging();
					this._CapacidadPasajeros = value;
					this.SendPropertyChanged("CapacidadPasajeros");
					this.OnCapacidadPasajerosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacidadCarga", DbType="VarChar(20)")]
		public string CapacidadCarga
		{
			get
			{
				return this._CapacidadCarga;
			}
			set
			{
				if ((this._CapacidadCarga != value))
				{
					this.OnCapacidadCargaChanging(value);
					this.SendPropertyChanging();
					this._CapacidadCarga = value;
					this.SendPropertyChanged("CapacidadCarga");
					this.OnCapacidadCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autonomia", DbType="Int")]
		public System.Nullable<int> Autonomia
		{
			get
			{
				return this._Autonomia;
			}
			set
			{
				if ((this._Autonomia != value))
				{
					this.OnAutonomiaChanging(value);
					this.SendPropertyChanging();
					this._Autonomia = value;
					this.SendPropertyChanged("Autonomia");
					this.OnAutonomiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAeronave_tblVuelo", Storage="_tblVuelos", ThisKey="IdAeronave", OtherKey="IdAeronave")]
		public EntitySet<tblVuelo> tblVuelos
		{
			get
			{
				return this._tblVuelos;
			}
			set
			{
				this._tblVuelos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblAeronave = this;
		}
		
		private void detach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblAeronave = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPiloto")]
	public partial class tblPiloto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPiloto;
		
		private string _Nombre;
		
		private string _Identificacion;
		
		private EntitySet<tblVuelo> _tblVuelos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPilotoChanging(int value);
    partial void OnIdPilotoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdentificacionChanging(string value);
    partial void OnIdentificacionChanged();
    #endregion
		
		public tblPiloto()
		{
			this._tblVuelos = new EntitySet<tblVuelo>(new Action<tblVuelo>(this.attach_tblVuelos), new Action<tblVuelo>(this.detach_tblVuelos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPiloto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPiloto
		{
			get
			{
				return this._IdPiloto;
			}
			set
			{
				if ((this._IdPiloto != value))
				{
					this.OnIdPilotoChanging(value);
					this.SendPropertyChanging();
					this._IdPiloto = value;
					this.SendPropertyChanged("IdPiloto");
					this.OnIdPilotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(20)")]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPiloto_tblVuelo", Storage="_tblVuelos", ThisKey="IdPiloto", OtherKey="IdPiloto")]
		public EntitySet<tblVuelo> tblVuelos
		{
			get
			{
				return this._tblVuelos;
			}
			set
			{
				this._tblVuelos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblPiloto = this;
		}
		
		private void detach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblPiloto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTrayecto")]
	public partial class tblTrayecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTrayecto;
		
		private string _Codigo;
		
		private string _Origen;
		
		private string _Destino;
		
		private string _Precio;
		
		private string _DuracionTrayecto;
		
		private string _Millas;
		
		private EntitySet<tblVuelo> _tblVuelos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTrayectoChanging(int value);
    partial void OnIdTrayectoChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnOrigenChanging(string value);
    partial void OnOrigenChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    partial void OnPrecioChanging(string value);
    partial void OnPrecioChanged();
    partial void OnDuracionTrayectoChanging(string value);
    partial void OnDuracionTrayectoChanged();
    partial void OnMillasChanging(string value);
    partial void OnMillasChanged();
    #endregion
		
		public tblTrayecto()
		{
			this._tblVuelos = new EntitySet<tblVuelo>(new Action<tblVuelo>(this.attach_tblVuelos), new Action<tblVuelo>(this.detach_tblVuelos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTrayecto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTrayecto
		{
			get
			{
				return this._IdTrayecto;
			}
			set
			{
				if ((this._IdTrayecto != value))
				{
					this.OnIdTrayectoChanging(value);
					this.SendPropertyChanging();
					this._IdTrayecto = value;
					this.SendPropertyChanged("IdTrayecto");
					this.OnIdTrayectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(15)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(20)")]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this.OnOrigenChanging(value);
					this.SendPropertyChanging();
					this._Origen = value;
					this.SendPropertyChanged("Origen");
					this.OnOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(20)")]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="VarChar(20)")]
		public string Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionTrayecto", DbType="VarChar(10)")]
		public string DuracionTrayecto
		{
			get
			{
				return this._DuracionTrayecto;
			}
			set
			{
				if ((this._DuracionTrayecto != value))
				{
					this.OnDuracionTrayectoChanging(value);
					this.SendPropertyChanging();
					this._DuracionTrayecto = value;
					this.SendPropertyChanged("DuracionTrayecto");
					this.OnDuracionTrayectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Millas", DbType="VarChar(15)")]
		public string Millas
		{
			get
			{
				return this._Millas;
			}
			set
			{
				if ((this._Millas != value))
				{
					this.OnMillasChanging(value);
					this.SendPropertyChanging();
					this._Millas = value;
					this.SendPropertyChanged("Millas");
					this.OnMillasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTrayecto_tblVuelo", Storage="_tblVuelos", ThisKey="IdTrayecto", OtherKey="IdTrayecto")]
		public EntitySet<tblVuelo> tblVuelos
		{
			get
			{
				return this._tblVuelos;
			}
			set
			{
				this._tblVuelos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblTrayecto = this;
		}
		
		private void detach_tblVuelos(tblVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblTrayecto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuario")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Identificacion;
		
		private string _MillasAcumuladas;
		
		private string _Clasificacion;
		
		private string _Pass;
		
		private string _Users;
		
		private string _Nombre;
		
		private string _Rol;
		
		private EntitySet<tblUsuarioVuelo> _tblUsuarioVuelos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdentificacionChanging(string value);
    partial void OnIdentificacionChanged();
    partial void OnMillasAcumuladasChanging(string value);
    partial void OnMillasAcumuladasChanged();
    partial void OnClasificacionChanging(string value);
    partial void OnClasificacionChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnUsersChanging(string value);
    partial void OnUsersChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    #endregion
		
		public tblUsuario()
		{
			this._tblUsuarioVuelos = new EntitySet<tblUsuarioVuelo>(new Action<tblUsuarioVuelo>(this.attach_tblUsuarioVuelos), new Action<tblUsuarioVuelo>(this.detach_tblUsuarioVuelos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(20)")]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MillasAcumuladas", DbType="VarChar(30)")]
		public string MillasAcumuladas
		{
			get
			{
				return this._MillasAcumuladas;
			}
			set
			{
				if ((this._MillasAcumuladas != value))
				{
					this.OnMillasAcumuladasChanging(value);
					this.SendPropertyChanging();
					this._MillasAcumuladas = value;
					this.SendPropertyChanged("MillasAcumuladas");
					this.OnMillasAcumuladasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasificacion", DbType="VarChar(15)")]
		public string Clasificacion
		{
			get
			{
				return this._Clasificacion;
			}
			set
			{
				if ((this._Clasificacion != value))
				{
					this.OnClasificacionChanging(value);
					this.SendPropertyChanging();
					this._Clasificacion = value;
					this.SendPropertyChanged("Clasificacion");
					this.OnClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(10)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Users", DbType="VarChar(10)")]
		public string Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				if ((this._Users != value))
				{
					this.OnUsersChanging(value);
					this.SendPropertyChanging();
					this._Users = value;
					this.SendPropertyChanged("Users");
					this.OnUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(1)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblUsuarioVuelo", Storage="_tblUsuarioVuelos", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<tblUsuarioVuelo> tblUsuarioVuelos
		{
			get
			{
				return this._tblUsuarioVuelos;
			}
			set
			{
				this._tblUsuarioVuelos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsuarioVuelos(tblUsuarioVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = this;
		}
		
		private void detach_tblUsuarioVuelos(tblUsuarioVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuarioVuelo")]
	public partial class tblUsuarioVuelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuVuelo;
		
		private System.Nullable<int> _IdVuelo;
		
		private System.Nullable<int> _IdUsuario;
		
		private string _PesoEquipaje;
		
		private EntityRef<tblUsuario> _tblUsuario;
		
		private EntityRef<tblVuelo> _tblVuelo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuVueloChanging(int value);
    partial void OnIdUsuVueloChanged();
    partial void OnIdVueloChanging(System.Nullable<int> value);
    partial void OnIdVueloChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    partial void OnPesoEquipajeChanging(string value);
    partial void OnPesoEquipajeChanged();
    #endregion
		
		public tblUsuarioVuelo()
		{
			this._tblUsuario = default(EntityRef<tblUsuario>);
			this._tblVuelo = default(EntityRef<tblVuelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuVuelo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuVuelo
		{
			get
			{
				return this._IdUsuVuelo;
			}
			set
			{
				if ((this._IdUsuVuelo != value))
				{
					this.OnIdUsuVueloChanging(value);
					this.SendPropertyChanging();
					this._IdUsuVuelo = value;
					this.SendPropertyChanged("IdUsuVuelo");
					this.OnIdUsuVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVuelo", DbType="Int")]
		public System.Nullable<int> IdVuelo
		{
			get
			{
				return this._IdVuelo;
			}
			set
			{
				if ((this._IdVuelo != value))
				{
					if (this._tblVuelo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVueloChanging(value);
					this.SendPropertyChanging();
					this._IdVuelo = value;
					this.SendPropertyChanged("IdVuelo");
					this.OnIdVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._tblUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoEquipaje", DbType="VarChar(15)")]
		public string PesoEquipaje
		{
			get
			{
				return this._PesoEquipaje;
			}
			set
			{
				if ((this._PesoEquipaje != value))
				{
					this.OnPesoEquipajeChanging(value);
					this.SendPropertyChanging();
					this._PesoEquipaje = value;
					this.SendPropertyChanged("PesoEquipaje");
					this.OnPesoEquipajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblUsuarioVuelo", Storage="_tblUsuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public tblUsuario tblUsuario
		{
			get
			{
				return this._tblUsuario.Entity;
			}
			set
			{
				tblUsuario previousValue = this._tblUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUsuario.Entity = null;
						previousValue.tblUsuarioVuelos.Remove(this);
					}
					this._tblUsuario.Entity = value;
					if ((value != null))
					{
						value.tblUsuarioVuelos.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVuelo_tblUsuarioVuelo", Storage="_tblVuelo", ThisKey="IdVuelo", OtherKey="IdVuelo", IsForeignKey=true)]
		public tblVuelo tblVuelo
		{
			get
			{
				return this._tblVuelo.Entity;
			}
			set
			{
				tblVuelo previousValue = this._tblVuelo.Entity;
				if (((previousValue != value) 
							|| (this._tblVuelo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblVuelo.Entity = null;
						previousValue.tblUsuarioVuelos.Remove(this);
					}
					this._tblVuelo.Entity = value;
					if ((value != null))
					{
						value.tblUsuarioVuelos.Add(this);
						this._IdVuelo = value.IdVuelo;
					}
					else
					{
						this._IdVuelo = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblVuelo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVuelo")]
	public partial class tblVuelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVuelo;
		
		private string _FechaSalida;
		
		private string _HoraSalida;
		
		private string _FechaRegreso;
		
		private string _HoraRegreso;
		
		private System.Nullable<int> _IdTrayecto;
		
		private System.Nullable<int> _IdAeronave;
		
		private System.Nullable<int> _IdPiloto;
		
		private System.Nullable<int> _CapacidadVuelo;
		
		private string _NombreVuelo;
		
		private EntitySet<tblUsuarioVuelo> _tblUsuarioVuelos;
		
		private EntityRef<tblAeronave> _tblAeronave;
		
		private EntityRef<tblPiloto> _tblPiloto;
		
		private EntityRef<tblTrayecto> _tblTrayecto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVueloChanging(int value);
    partial void OnIdVueloChanged();
    partial void OnFechaSalidaChanging(string value);
    partial void OnFechaSalidaChanged();
    partial void OnHoraSalidaChanging(string value);
    partial void OnHoraSalidaChanged();
    partial void OnFechaRegresoChanging(string value);
    partial void OnFechaRegresoChanged();
    partial void OnHoraRegresoChanging(string value);
    partial void OnHoraRegresoChanged();
    partial void OnIdTrayectoChanging(System.Nullable<int> value);
    partial void OnIdTrayectoChanged();
    partial void OnIdAeronaveChanging(System.Nullable<int> value);
    partial void OnIdAeronaveChanged();
    partial void OnIdPilotoChanging(System.Nullable<int> value);
    partial void OnIdPilotoChanged();
    partial void OnCapacidadVueloChanging(System.Nullable<int> value);
    partial void OnCapacidadVueloChanged();
    partial void OnNombreVueloChanging(string value);
    partial void OnNombreVueloChanged();
    #endregion
		
		public tblVuelo()
		{
			this._tblUsuarioVuelos = new EntitySet<tblUsuarioVuelo>(new Action<tblUsuarioVuelo>(this.attach_tblUsuarioVuelos), new Action<tblUsuarioVuelo>(this.detach_tblUsuarioVuelos));
			this._tblAeronave = default(EntityRef<tblAeronave>);
			this._tblPiloto = default(EntityRef<tblPiloto>);
			this._tblTrayecto = default(EntityRef<tblTrayecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVuelo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVuelo
		{
			get
			{
				return this._IdVuelo;
			}
			set
			{
				if ((this._IdVuelo != value))
				{
					this.OnIdVueloChanging(value);
					this.SendPropertyChanging();
					this._IdVuelo = value;
					this.SendPropertyChanged("IdVuelo");
					this.OnIdVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="VarChar(12)")]
		public string FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this.OnFechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._FechaSalida = value;
					this.SendPropertyChanged("FechaSalida");
					this.OnFechaSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraSalida", DbType="VarChar(5)")]
		public string HoraSalida
		{
			get
			{
				return this._HoraSalida;
			}
			set
			{
				if ((this._HoraSalida != value))
				{
					this.OnHoraSalidaChanging(value);
					this.SendPropertyChanging();
					this._HoraSalida = value;
					this.SendPropertyChanged("HoraSalida");
					this.OnHoraSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegreso", DbType="VarChar(12)")]
		public string FechaRegreso
		{
			get
			{
				return this._FechaRegreso;
			}
			set
			{
				if ((this._FechaRegreso != value))
				{
					this.OnFechaRegresoChanging(value);
					this.SendPropertyChanging();
					this._FechaRegreso = value;
					this.SendPropertyChanged("FechaRegreso");
					this.OnFechaRegresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegreso", DbType="VarChar(5)")]
		public string HoraRegreso
		{
			get
			{
				return this._HoraRegreso;
			}
			set
			{
				if ((this._HoraRegreso != value))
				{
					this.OnHoraRegresoChanging(value);
					this.SendPropertyChanging();
					this._HoraRegreso = value;
					this.SendPropertyChanged("HoraRegreso");
					this.OnHoraRegresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTrayecto", DbType="Int")]
		public System.Nullable<int> IdTrayecto
		{
			get
			{
				return this._IdTrayecto;
			}
			set
			{
				if ((this._IdTrayecto != value))
				{
					if (this._tblTrayecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTrayectoChanging(value);
					this.SendPropertyChanging();
					this._IdTrayecto = value;
					this.SendPropertyChanged("IdTrayecto");
					this.OnIdTrayectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAeronave", DbType="Int")]
		public System.Nullable<int> IdAeronave
		{
			get
			{
				return this._IdAeronave;
			}
			set
			{
				if ((this._IdAeronave != value))
				{
					if (this._tblAeronave.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAeronaveChanging(value);
					this.SendPropertyChanging();
					this._IdAeronave = value;
					this.SendPropertyChanged("IdAeronave");
					this.OnIdAeronaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPiloto", DbType="Int")]
		public System.Nullable<int> IdPiloto
		{
			get
			{
				return this._IdPiloto;
			}
			set
			{
				if ((this._IdPiloto != value))
				{
					if (this._tblPiloto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPilotoChanging(value);
					this.SendPropertyChanging();
					this._IdPiloto = value;
					this.SendPropertyChanged("IdPiloto");
					this.OnIdPilotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacidadVuelo", DbType="Int")]
		public System.Nullable<int> CapacidadVuelo
		{
			get
			{
				return this._CapacidadVuelo;
			}
			set
			{
				if ((this._CapacidadVuelo != value))
				{
					this.OnCapacidadVueloChanging(value);
					this.SendPropertyChanging();
					this._CapacidadVuelo = value;
					this.SendPropertyChanged("CapacidadVuelo");
					this.OnCapacidadVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreVuelo", DbType="VarChar(50)")]
		public string NombreVuelo
		{
			get
			{
				return this._NombreVuelo;
			}
			set
			{
				if ((this._NombreVuelo != value))
				{
					this.OnNombreVueloChanging(value);
					this.SendPropertyChanging();
					this._NombreVuelo = value;
					this.SendPropertyChanged("NombreVuelo");
					this.OnNombreVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVuelo_tblUsuarioVuelo", Storage="_tblUsuarioVuelos", ThisKey="IdVuelo", OtherKey="IdVuelo")]
		public EntitySet<tblUsuarioVuelo> tblUsuarioVuelos
		{
			get
			{
				return this._tblUsuarioVuelos;
			}
			set
			{
				this._tblUsuarioVuelos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAeronave_tblVuelo", Storage="_tblAeronave", ThisKey="IdAeronave", OtherKey="IdAeronave", IsForeignKey=true)]
		public tblAeronave tblAeronave
		{
			get
			{
				return this._tblAeronave.Entity;
			}
			set
			{
				tblAeronave previousValue = this._tblAeronave.Entity;
				if (((previousValue != value) 
							|| (this._tblAeronave.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAeronave.Entity = null;
						previousValue.tblVuelos.Remove(this);
					}
					this._tblAeronave.Entity = value;
					if ((value != null))
					{
						value.tblVuelos.Add(this);
						this._IdAeronave = value.IdAeronave;
					}
					else
					{
						this._IdAeronave = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblAeronave");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPiloto_tblVuelo", Storage="_tblPiloto", ThisKey="IdPiloto", OtherKey="IdPiloto", IsForeignKey=true)]
		public tblPiloto tblPiloto
		{
			get
			{
				return this._tblPiloto.Entity;
			}
			set
			{
				tblPiloto previousValue = this._tblPiloto.Entity;
				if (((previousValue != value) 
							|| (this._tblPiloto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPiloto.Entity = null;
						previousValue.tblVuelos.Remove(this);
					}
					this._tblPiloto.Entity = value;
					if ((value != null))
					{
						value.tblVuelos.Add(this);
						this._IdPiloto = value.IdPiloto;
					}
					else
					{
						this._IdPiloto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblPiloto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTrayecto_tblVuelo", Storage="_tblTrayecto", ThisKey="IdTrayecto", OtherKey="IdTrayecto", IsForeignKey=true)]
		public tblTrayecto tblTrayecto
		{
			get
			{
				return this._tblTrayecto.Entity;
			}
			set
			{
				tblTrayecto previousValue = this._tblTrayecto.Entity;
				if (((previousValue != value) 
							|| (this._tblTrayecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTrayecto.Entity = null;
						previousValue.tblVuelos.Remove(this);
					}
					this._tblTrayecto.Entity = value;
					if ((value != null))
					{
						value.tblVuelos.Add(this);
						this._IdTrayecto = value.IdTrayecto;
					}
					else
					{
						this._IdTrayecto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblTrayecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsuarioVuelos(tblUsuarioVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblVuelo = this;
		}
		
		private void detach_tblUsuarioVuelos(tblUsuarioVuelo entity)
		{
			this.SendPropertyChanging();
			entity.tblVuelo = null;
		}
	}
}
#pragma warning restore 1591
